### ISSUE TITLE
What I am doing

### ISSUE THREAD

**Issue by jhernancanom** [billand88/ChilkatVFP#1]
Good morning, friend.
I have download and I have run the sample, but I am getting errs.
I would like you to help me to resolve them.

In attached PDF I show what I am doing.

Thanks.
[What I am doing.pdf](https://github.com/billand88/ChilkatVFP/files/10369920/What.I.am.doing.pdf)

**Comment by billand88** [comment]
ChilkatVFP is a wrapper around the Chilkat API. You need to download and install Chilkat from here: https://www.chilkatsoft.com/downloads_ActiveX.asp

**Comment by jhernancanom** [comment]
I installed chilkatax-9.5.0-x64.zip
I run register.bat; I received Ok.
I run testCreateObject.bat; It seems Ok; I received version and....
![image](https://user-images.githubusercontent.com/5818845/211378988-5779d06b-5d4c-4ef0-86fd-d95be93dc56e.png)

I run EXAMPLE.PRG; I received first: Property LASTBINARYRESULT is not found.
Next I received: Cannot open MsgSvc table! (the MsgSvc.FPT lacks !!!  Cannot you see?)
And finally: the ChilkatLog Blocking Upload.

Thanks for sharing.

[Infelicities.md](https://github.com/billand88/ChilkatVFP/files/10375931/Infelicities.md)
![image](https://user-images.githubusercontent.com/5818845/211382592-d24dcff5-d4c4-41f8-88c7-d5c8ca1de242.png)
